export const tolsData = [
    {
        "id":1,
        "common_name":"Promotheus",
    },
    {
        "id":2,
        "common_name":"Loki",
    },
    {
        "id":3,
        "common_name":"Bitbucket",
    },
    {
        "id":4,
        "common_name":"Gitlab",
    },
    {
        "id":5,
        "common_name":"Kotlin",
    },
    {
        "id":6,
        "common_name":"Android ",
    },
    {
        "id":7,
        "common_name":" Java",
    },
    {
        "id":8,
        "common_name":"Azure ",
    },
    {
        "id":9,
        "common_name":"GCP",
    },
    {
        "id":10,
        "common_name":"DigitalOcean",
    },
    {
        "id":11,
        "common_name":"AWS",
    },
    {
        "id":12,
        "common_name":"Kubernets",
    },
    {
        "id":13,
        "common_name":"ELK",
    },
    {
        "id":14,
        "common_name":"Grafana",
    },
    {
        "id":15,
        "common_name":"Terraform",
    },
    {
        "id":16,
        "common_name":"IOS",
    },
    {
        "id":17,
        "common_name":"Swift",
    },
    {
        "id":18,
        "common_name":"Flutter",
    },
    {
        "id":19,
        "common_name":"Next JS",
    },
    {
        "id":20,
        "common_name":"React JS",
    },
    {
        "id":21,
        "common_name":"JavaScript",
    },
    {
        "id":22,
        "common_name":"Balsamic",
    },
    {
        "id":23,
        "common_name":"Invision",
    },
    {
        "id":24,
        "common_name":"Figma",
    },
    {
        "id":25,
        "common_name":"Docker",
    },
    {
        "id":26,
        "common_name":"PostgreSQL",
    },
    {
        "id":27,
        "common_name":"Python",
    },
    {
        "id":28,
        "common_name":"NodeJS",
    },
    {
        "id":29,
        "common_name":"PHP",
    },
    {
        "id":30,
        "common_name":"GO",
    },
    {
        "id":31,
        "common_name":"ANT Design",
    },
    {
        "id":32,
        "common_name":"Gatsby JS",
    },
    {
        "id":33,
        "common_name":"VUE JS",
    },
    {
        "id":34,
        "common_name":"Principle",
    },
    {
        "id":35,
        "common_name":"Sketch",
    },
    {
        "id":36,
        "common_name":"Adobe suite",
    },
    {
        "id":37,
        "common_name":"YouTrack",
    },
    {
        "id":38,
        "common_name":"Appium",
    },
    {
        "id":39,
        "common_name":"Cypers",
    },
    {
        "id":40,
        "common_name":"MongoDB",
    },
    {
        "id":41,
        "common_name":"Cassandra",
    },
    {
        "id":42,
        "common_name":"Sass",
    },
    {
        "id":43,
        "common_name":"Material Ui",
    },
    {
        "id":44,
        "common_name":"Zepline",
    },
    {
        "id":45,
        "common_name":"ILIsturator",
    },
    {
        "id":46,
        "common_name":"Lottie",
    },
    {
        "id":47,
        "common_name":"Photoshop",
    },
    {
        "id":48,
        "common_name":"MongoDB",
    },
]